In [1]:
import train_ml as mlp
import pipe_line as pline
import torch

In [2]:
session = pline.pipe_line("pipeline.yml")
ml_session = mlp.machine_learn_predict()

In [3]:
bhp_df = session.pull_dt("BHP")

In [4]:
learn_superset = ml_session.get_learn_dat(bhp_df,"close_price")
train_set, test_set = ml_session.apportion_train_set(learn_superset)

In [5]:
ml_session.generate_ml()

In [6]:
ml_session.train_ml(train_set, 1000)

lstm(
  (lstm): LSTM(1, 1)
)


GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name | Type | Params
------------------------------
0 | lstm | LSTM | 16    
------------------------------
16        Trainable params
0         Non-trainable params
16        Total params
0.000     Total estimated model params size (MB)
C:\Users\user\anaconda3\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:430: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 4 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(


Training: 0it [00:00, ?it/s]

C:\Users\user\Documents\Python Scripts\Projects\TraderTool\train_ml.py:44: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  loss = torch.tensor(loss, requires_grad = True)
`Trainer.fit` stopped: `max_epochs=1000` reached.


True

In [13]:
ml_session.model(train_set[0][0]) - train_set[0][1]



tensor([-37.2700], grad_fn=<SubBackward0>)

In [15]:
train_set[0][1]

tensor(37.2700)

AssertionError: LSTM: Expected input to be 2-D or 3-D but received 1-D tensor

In [21]:
input_i, label_i = train_set[0]

In [22]:
input_i

tensor([38.6000, 39.3000, 39.4100, 38.0900])

In [23]:
label_i

tensor(36.2700)

In [24]:

pred = ml_session.model.forward(train_set[0][0])

tensor(-7.9564e-17, grad_fn=<SelectBackward0>)


In [25]:
pred.detach()

tensor(-7.9564e-17)

In [26]:
import torch
import numpy as np
loss = torch.tensor(np.array((pred.detach() - label_i)**2))

In [14]:
loss

tensor([1414.5626])

In [15]:
label_i

tensor(38.6100)

In [30]:
torch.column_stack([input_i, input_i])

tensor([[38.6000, 38.6000],
        [39.3000, 39.3000],
        [39.4100, 39.4100],
        [38.0900, 38.0900]])